// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ClientDiff.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace NebulaProtoGen
{

	[global::ProtoBuf.ProtoContract()]
	public partial class ClientDiff : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"diff")]
		public global::System.Collections.Generic.List<FileDiff> Diffs { get; } = new global::System.Collections.Generic.List<FileDiff>();

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class FileDiff : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"file_name")]
		[global::System.ComponentModel.DefaultValue("")]
		public string FileName { get; set; } = "";

		[global::ProtoBuf.ProtoMember(2, Name = @"hash")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Hash { get; set; } = "";

		[global::ProtoBuf.ProtoMember(3, Name = @"version")]
		public long Version { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"additional_path")]
		[global::System.ComponentModel.DefaultValue("")]
		public string AdditionalPath { get; set; } = "";

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class FileDiffList : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"diff_list")]
		[global::ProtoBuf.ProtoMap]
		public global::System.Collections.Generic.Dictionary<string, ClientDiff> DiffLists { get; } = new global::System.Collections.Generic.Dictionary<string, ClientDiff>();

	}

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
