namespace unluac.decompile
{
	public enum Op
	{
		MOVE, LOADK, LOADBOOL, LOADNIL, GETUPVAL, GETGLOBAL, GETTABLE, SETGLOBAL, SETUPVAL, SETTABLE, NEWTABLE, SELF,
		ADD, SUB, MUL, DIV, MOD, POW, UNM, NOT, LEN, CONCAT, JMP, EQ, LT, LE, TEST, TESTSET, CALL, TAILCALL, RETURN,
		FORLOOP, FORPREP, TFORLOOP, SETLIST, CLOSE, CLOSURE, VARARG,
		LOADKX, GETTABUP, SETTABUP, TFORCALL, EXTRAARG,
		NEWTABLE50, SETLIST50, SETLISTO, TFORPREP, TEST50,
		IDIV, BAND, BOR, BXOR, SHL, SHR, BNOT
	}
}
